# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
